### ISSUE TITLE
Bad credentials error with default token and self hosted runners

### ISSUE THREAD

**Issue by pmeyerra** [kenji-miyake/setup-git-cliff#64]
The version 1.1.0 of this actions fails when run from a self hosted GitHub Action runner connected to an on-premise GitHub Enterprise instance.

I believe the problem is that `${{ github.token }}`  is used as default for the token. When running on a self hosted runner connected to an on premise GitHub Enterprise instance, this token will not be valid for `https://api.github.com`, resulting in a Bad credentials error.

```text
/tmp/github_actions_runners/2/_actions/kenji-miyake/setup-git-cliff/v1/dist/index.js:6181
      const error = new requestError.RequestError(toErrorMessage(data), status, {
                    ^

RequestError [HttpError]: Bad credentials
    at /tmp/github_actions_runners/2/_actions/kenji-miyake/setup-git-cliff/v1/dist/index.js:6181:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (/tmp/github_actions_runners/2/_actions/kenji-miyake/setup-git-cliff/v1/dist/index.js:13281:31) {
  status: 401,
  response: {
    url: 'https://api.github.com/repos/orhun/git-cliff/releases/latest',
    status: 401,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      connection: 'close',
      'content-length': '80',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Thu, 05 Jan 2023 11:58:02 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': 'B344:0447:39F3109:7669C32:63B6BB4A',
      'x-ratelimit-limit': '60',
      'x-ratelimit-remaining': '59',
      'x-ratelimit-reset': '1672923482',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '1',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Bad credentials',
      documentation_url: 'https://docs.github.com/rest'
    }
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/orhun/git-cliff/releases/latest',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/19.0.5 octokit-core.js/4.1.0 Node.js/16.13.0 (linux; x64)',
      authorization: 'token [REDACTED]'
    },
    request: { hook: [Function: bound bound register] }
  }
}
```

Would it be possible to remove the default value or at least update the documentation and specify which value the `token` variable should be set to for it to be ignored?

**Comment by kenji-miyake** [comment]
@pmeyerra Thank you for reporting this. I wouldn't like to remove it because the default value is necessary for my use case and I feel your use case is a little rare case.
However, I will gladly merge document updates if you send a PR.
Is that okay for you?

**Comment by pmeyerra** [comment]
I've opened #65. Let me know if that works for you 😄
